In [28]:
import numpy as np
def knapsack_DP(w,v,capacity):
    n=len(v)
    M=np.zeros((n+1,capacity+1))
    for i in range(n+1):
        for j in range(capacity+1):
            if i == 0 or j == 0:
                M[i,j] = 0
            elif w[i-1]<=j:
                M[i,j]=max(v[i-1]+M[i-1,j-w[i-1]],M[i-1,j])
            else:
                M[i,j]=M[i-1,j]
    
    print(M)
    return M[n,capacity]

w=[1,3,5,4,1,3,2]
v=[5,10,15,7,8,9,4]
capacity=15
print(knapsack_DP(w,v,capacity))

[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  5.  5.  5.  5.  5.  5.  5.  5.  5.  5.  5.  5.  5.  5.  5.]
 [ 0.  5.  5. 10. 15. 15. 15. 15. 15. 15. 15. 15. 15. 15. 15. 15.]
 [ 0.  5.  5. 10. 15. 15. 20. 20. 25. 30. 30. 30. 30. 30. 30. 30.]
 [ 0.  5.  5. 10. 15. 15. 20. 20. 25. 30. 30. 30. 32. 37. 37. 37.]
 [ 0.  8. 13. 13. 18. 23. 23. 28. 28. 33. 38. 38. 38. 40. 45. 45.]
 [ 0.  8. 13. 13. 18. 23. 23. 28. 32. 33. 38. 38. 42. 47. 47. 47.]
 [ 0.  8. 13. 13. 18. 23. 23. 28. 32. 33. 38. 38. 42. 47. 47. 51.]]
51.0
